name: Tourism Project
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # if the csv is tracked with Git LFS

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install "huggingface_hub>=0.23"

      - name: run data_register.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism_package_pred/model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "huggingface_hub>=0.23" pandas scikit-learn hf_transfer

      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_package_pred/model_building/prep.py

  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn "xgboost>=1.7,<2.1" "mlflow>=2.12" pandas numpy "huggingface_hub>=0.23" joblib

      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 >/dev/null 2>&1 &
          sleep 5      
      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_package_pred/model_building/train.py
          
  deploy-hosting:
    needs: [model-traning, data-prep, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "huggingface_hub>=0.23"
          pip -q install streamlit
      - name: Deployment
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_package_pred/hosting/hosting.py
          python tourism_package_pred/deployment/app.py
